# Generated by Django 3.1.6 on 2021-02-15 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210215_0916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='name',
            field=models.CharField(default='random task', max_length=200),
            preserve_default=False,
        ),
    ]
