# Generated by Django 3.1.6 on 2021-02-17 02:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20210216_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtask',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
